apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.lc_app.fullname }}
  labels:
    app: {{ .Values.lc_app.name }}
spec:
  replicas: 1 # Number of replicated pods
  selector:
    matchLabels:
      app: {{ .Values.lc_app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.lc_app.name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080 # Open pod port 80 for the container
          livenessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 1
          env: # [OPTIONAL] add environments values
            - name: MONGO_HOST
              value: lc-db
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: lc-db
                  key: username
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: lc-db
                  key: password
