global:
  host: k8s-training.com

  app:
    service:
      name: app
      port: 8080
  cache:
    service:
      name: cache
      port: 6379
  db:
    service:
      name: db
      port: 27017

app:
  persistent:
    enabled: false
    nfs:
      server: 172.17.0.1
      path: /mnt/nfs_share
db:
  persistent:
    enabled: false
